export interface GoogleFontOption {
  family: string
  category: 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace'
}

export const GOOGLE_FONTS: GoogleFontOption[] = [
  { family: 'Inter', category: 'sans-serif' },
  { family: 'Manrope', category: 'sans-serif' },
  { family: 'DM Sans', category: 'sans-serif' },
  { family: 'Plus Jakarta Sans', category: 'sans-serif' },
  { family: 'Space Grotesk', category: 'sans-serif' },
  { family: 'Poppins', category: 'sans-serif' },
  { family: 'Outfit', category: 'sans-serif' },
  { family: 'Urbanist', category: 'sans-serif' },
  { family: 'Work Sans', category: 'sans-serif' },
  { family: 'Nunito', category: 'sans-serif' },
  { family: 'Rubik', category: 'sans-serif' },
  { family: 'Open Sans', category: 'sans-serif' },
  { family: 'Roboto', category: 'sans-serif' },
  { family: 'Lato', category: 'sans-serif' },
  { family: 'Montserrat', category: 'sans-serif' },
  { family: 'Raleway', category: 'sans-serif' },
  { family: 'Source Sans Pro', category: 'sans-serif' },
  { family: 'Sora', category: 'sans-serif' },
  { family: 'Figtree', category: 'sans-serif' },
  { family: 'Lexend', category: 'sans-serif' },
  { family: 'Quicksand', category: 'sans-serif' },
  { family: 'Comfortaa', category: 'sans-serif' },
  { family: 'Bebas Neue', category: 'display' },
  { family: 'Oswald', category: 'sans-serif' },
  { family: 'Anton', category: 'sans-serif' },
  { family: 'Barlow', category: 'sans-serif' },
  { family: 'Mulish', category: 'sans-serif' },
  { family: 'Archivo', category: 'sans-serif' },
  { family: 'Syne', category: 'sans-serif' },
  { family: 'Unbounded', category: 'sans-serif' },
  { family: 'Public Sans', category: 'sans-serif' },
  { family: 'Karla', category: 'sans-serif' },
  { family: 'Epilogue', category: 'sans-serif' },
  { family: 'Noto Sans', category: 'sans-serif' },
  { family: 'Jost', category: 'sans-serif' },
  { family: 'Varela Round', category: 'sans-serif' },
  { family: 'Kanit', category: 'sans-serif' },
  { family: 'Chivo', category: 'sans-serif' },
  { family: 'Fira Sans', category: 'sans-serif' },
  { family: 'Overpass', category: 'sans-serif' },
  { family: 'Exo 2', category: 'sans-serif' },
  { family: 'Rajdhani', category: 'sans-serif' },
  { family: 'Titillium Web', category: 'sans-serif' },
  { family: 'Hanken Grotesk', category: 'sans-serif' },
  { family: 'Onest', category: 'sans-serif' },
  { family: 'Albert Sans', category: 'sans-serif' },
  { family: 'Commissioner', category: 'sans-serif' },
  { family: 'Readex Pro', category: 'sans-serif' },
  { family: 'Schibsted Grotesk', category: 'sans-serif' },
  { family: 'Nunito Sans', category: 'sans-serif' },
  { family: 'Playfair Display', category: 'serif' },
  { family: 'Lora', category: 'serif' },
  { family: 'Merriweather', category: 'serif' },
  { family: 'Libre Baskerville', category: 'serif' },
  { family: 'Cormorant', category: 'serif' },
  { family: 'Cormorant Garamond', category: 'serif' },
  { family: 'EB Garamond', category: 'serif' },
  { family: 'Crimson Text', category: 'serif' },
  { family: 'Source Serif Pro', category: 'serif' },
  { family: 'Bitter', category: 'serif' },
  { family: 'Spectral', category: 'serif' },
  { family: 'Cardo', category: 'serif' },
  { family: 'Domine', category: 'serif' },
  { family: 'Fraunces', category: 'serif' },
  { family: 'Newsreader', category: 'serif' },
  { family: 'Literata', category: 'serif' },
  { family: 'PT Serif', category: 'serif' },
  { family: 'Noto Serif', category: 'serif' },
  { family: 'Crimson Pro', category: 'serif' },
  { family: 'Playfair', category: 'serif' },
  { family: 'Vollkorn', category: 'serif' },
  { family: 'Alegreya', category: 'serif' },
  { family: 'Zilla Slab', category: 'serif' },
  { family: 'Roboto Slab', category: 'serif' },
  { family: 'Arvo', category: 'serif' },
  { family: 'Instrument Serif', category: 'serif' },
  { family: 'Fira Code', category: 'monospace' },
  { family: 'JetBrains Mono', category: 'monospace' },
  { family: 'Source Code Pro', category: 'monospace' },
  { family: 'IBM Plex Mono', category: 'monospace' },
  { family: 'Roboto Mono', category: 'monospace' },
  { family: 'Space Mono', category: 'monospace' },
  { family: 'Inconsolata', category: 'monospace' },
  { family: 'Overpass Mono', category: 'monospace' },
  { family: 'DM Mono', category: 'monospace' },
  { family: 'Azeret Mono', category: 'monospace' },
  { family: 'Spline Sans Mono', category: 'monospace' },
  { family: 'Noto Sans Mono', category: 'monospace' },
  { family: 'Cascadia Code', category: 'monospace' },
  { family: 'Victor Mono', category: 'monospace' },
  { family: 'Ubuntu Mono', category: 'monospace' },
  { family: 'Dancing Script', category: 'handwriting' },
  { family: 'Pacifico', category: 'handwriting' },
  { family: 'Caveat', category: 'handwriting' },
  { family: 'Satisfy', category: 'handwriting' },
  { family: 'Great Vibes', category: 'handwriting' },
  { family: 'Permanent Marker', category: 'handwriting' },
  { family: 'Lobster', category: 'display' },
  { family: 'Righteous', category: 'display' },
  { family: 'Russo One', category: 'display' },
  { family: 'Bangers', category: 'display' },
  { family: 'Fredoka', category: 'display' },
  { family: 'Baloo 2', category: 'display' },
  { family: 'Orbitron', category: 'display' },
  { family: 'Audiowide', category: 'display' },
  { family: 'Press Start 2P', category: 'display' },
  { family: 'Silkscreen', category: 'display' },
  { family: 'Pixelify Sans', category: 'sans-serif' },
  { family: 'Geologica', category: 'sans-serif' },
  { family: 'Mona Sans', category: 'sans-serif' },
  { family: 'General Sans', category: 'sans-serif' },
  { family: 'Cabinet Grotesk', category: 'sans-serif' },
  { family: 'Satoshi', category: 'sans-serif' },
  { family: 'Neue Montreal', category: 'sans-serif' },
  { family: 'Red Hat Display', category: 'sans-serif' },
  { family: 'Barlow Condensed', category: 'sans-serif' },
  { family: 'Teko', category: 'sans-serif' },
  { family: 'Chakra Petch', category: 'sans-serif' },
  { family: 'Courier Prime', category: 'monospace' },
]

export const FONT_CATEGORIES = ['all', 'sans-serif', 'serif', 'monospace', 'display', 'handwriting'] as const

export function getFontsByCategory(category: string): GoogleFontOption[] {
  if (category === 'all') return GOOGLE_FONTS
  return GOOGLE_FONTS.filter(f => f.category === category)
}
