import { Agent } from "agents";
import { generateObject } from "ai";
import { z } from "zod";
import { createAdvancedModelChain, resolveProviderConfig } from "../ai/providers";

interface Env {
  AI: Ai;
  AI_GATEWAY_TOKEN?: string;
  GOOGLE_API_KEY?: string;
}

interface PromptProfilePayload {
  mastermind: string[];
  strategist: string[];
  copywriter: string[];
  visualDirector: string[];
  renderGuard: string[];
}

interface RenderPolicyPayload {
  allowMarkdown: boolean;
  allowMath: boolean;
  allowDiagrams: boolean;
  allowTextInAiImages: boolean;
}

interface ImageSpec {
  /** Type of image: background, illustration, pattern, gradient, feature, none */
  type: string;
  /** AI prompt for generation (if type is ai-generated) */
  prompt?: string;
  /** Position in HTML: background, hero, left, right, overlay */
  position: string;
  /** Number of images (for carousels) */
  count?: number;
  /** Style hints for AI generation */
  style?: string;
}

interface PostBrief {
  format: string;
  brief: string;
  copyFocus: string;
  visualDirection: string;
  cta: string;
  /** Image mode: auto, none, feature, ai */
  imageMode?: string;
  /** Detailed image specification for this post */
  imageSpec?: ImageSpec;
  width?: number;
  height?: number;
}

interface WorkspaceSettings {
  brand?: {
    name?: string;
    tone?: string;
    audience?: string;
  };
  campaign?: {
    goal?: string;
    framework?: string;
    cta?: string;
    hashtags?: {
      style?: string;
      count?: number;
    };
  };
  formats?: {
    enabled?: string[];
    postCount?: number;
  };
  image?: {
    mode?: string;
  };
  templates?: {
    autoSelect?: boolean;
  };
}

interface OrchestratorRequestPayload {
  post: {
    title: string;
    excerpt?: string;
    plaintext?: string;
    tags?: string[];
  };
  requestedFormats: string[];
  userPrompt?: string;
  promptProfile: PromptProfilePayload;
  renderPolicy: RenderPolicyPayload;
  postCount?: number;
  settings?: WorkspaceSettings;
  imageConfig?: {
    mode: string;
  };
}

interface OrchestratorResponsePayload {
  strategic_brief: string;
  copywriter_notes: string;
  visual_notes: string;
  warnings: string[];
  /** Planned posts with individual briefs - generated by gemma-4 */
  plannedPosts?: PostBrief[];
  /** Whether to use the advanced gemma-4 model */
  useAdvancedModel?: boolean;
}

const ORCHESTRATOR_SCHEMA = z.object({
  strategic_brief: z.string(),
  copywriter_notes: z.string(),
  visual_notes: z.string(),
  warnings: z.array(z.string()),
  plannedPosts: z.array(z.object({
    format: z.string(),
    brief: z.string(),
    copyFocus: z.string(),
    visualDirection: z.string(),
    cta: z.string(),
    imageMode: z.string().optional(),
    imageSpec: z.object({
      type: z.string(),
      prompt: z.string().optional(),
      position: z.string(),
      count: z.number().optional(),
      style: z.string().optional(),
    }).optional(),
    width: z.number().optional(),
    height: z.number().optional(),
  })).optional(),
});

export class MarketingOrchestratorAgent extends Agent<Env> {
  async onRequest(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (request.method !== "POST" || url.pathname !== "/orchestrate") {
      return json({ error: "Not found" }, 404);
    }

    const payload = await parseRequestPayload(request);
    if (!payload) {
      return json({ error: "Invalid JSON payload" }, 400);
    }

    const result = await this.plan(payload);
    return json(result);
  }

  private async plan(input: OrchestratorRequestPayload): Promise<OrchestratorResponsePayload> {
    const sourceBody = (input.post.plaintext ?? "").trim();
    const sourceExcerpt = (input.post.excerpt ?? "").trim();
    const sourceText = sourceBody || sourceExcerpt;
    const truncatedSource = sourceText.length > 14000 ? `${sourceText.slice(0, 14000)}...` : sourceText;

    const tags = (input.post.tags ?? []).slice(0, 8).join(", ");
    const requestedFormats = input.requestedFormats.join(", ");
    const userPrompt = input.userPrompt?.trim() || "(none)";
    const postCount = input.postCount || input.requestedFormats.length;

    const settings = input.settings || {};
    const imageConfig = input.imageConfig || { mode: 'auto' };
    
    const brandInfo = settings.brand ? 
      `Brand: ${settings.brand.name || 'unnamed'} | Tone: ${settings.brand.tone || 'neutral'} | Audience: ${settings.brand.audience || 'general'}` : 
      'Brand: not configured';
    const campaignInfo = settings.campaign ?
      `Goal: ${settings.campaign.goal || 'awareness'} | Framework: ${settings.campaign.framework || 'none'} | CTA: ${settings.campaign.cta || 'none'}` :
      'Campaign: not configured';
    const imageMode = imageConfig.mode || 'auto';

    const policyNotes = [
      `allow_markdown=${input.renderPolicy.allowMarkdown}`,
      `allow_math=${input.renderPolicy.allowMath}`,
      `allow_diagrams=${input.renderPolicy.allowDiagrams}`,
      `allow_text_in_ai_images=${input.renderPolicy.allowTextInAiImages}`
    ].join(", ");

    const systemPrompt = [
      ...input.promptProfile.mastermind,
      ...input.promptProfile.strategist,
      ...input.promptProfile.copywriter,
      ...input.promptProfile.visualDirector,
      ...input.promptProfile.renderGuard,
      "Return strict JSON matching the required response schema."
    ].filter(Boolean).join("\n");

    const prompt = [
      `Build a creative campaign orchestration decision for social content generation.`,
      "",
      `IMPORTANT: Plan ${postCount} posts from this content.`,
      "",
      `=== CONFIGURATION ===`,
      brandInfo,
      campaignInfo,
      `Image mode: ${imageMode} (options: auto, none, feature, ai)`,
      `Available formats: ${requestedFormats || "(none)"}`,
      "",
      `=== CONTENT ===`,
      `<title>${input.post.title.trim()}</title>`,
      `<excerpt>${sourceExcerpt || "(none)"}</excerpt>`,
      `<tags>${tags || "(none)"}</tags>`,
      "<body>",
      truncatedSource || "(none)",
      "</body>",
      "",
      `=== RENDER POLICY ===`,
      policyNotes,
      "",
      `User prompt: ${userPrompt}`,
      "",
      "Produce:",
      "- strategic_brief: campaign intent, creative angle, and hook strategy",
      "- copywriter_notes: platform tone, structure, and copy direction",
      "- visual_notes: image direction and composition guidance",
      "- warnings: potential quality/compliance risks",
      "",
      `IMPORTANT: Also produce a "plannedPosts" array with ${postCount} entries, one for each planned post. Each entry should have:`,
      "- format: the social platform/format - MUST be one of: " + (requestedFormats || 'linkedin,twitter,instagram'),
      "- brief: a 1-2 sentence creative brief for this specific post",
      "- copyFocus: what angle/perspective to take for the copy",
      "- visualDirection: visual style guidance for this post (consider image mode: " + imageMode + ")",
      "- cta: specific call-to-action for this format",
      "- imageMode: recommended image generation mode (auto/none/feature/ai). If set to 'ai', you MUST provide an imageSpec and a detailed prompt.",
      "- imageSpec: detailed image specification with:",
      "  * type: background | illustration | pattern | gradient | feature | none",
      "  * prompt: AI generation prompt. REQUIRED if imageMode is 'ai'. Describe visual, no text.",
      "  * position: background | hero | left | right | overlay",
      "  * count: number of images for carousel (1-5)",
      "  * style: style hints (minimal, bold, abstract, realistic, etc.)",
      "- width: recommended width for this format",
      "- height: recommended height for this format",
      "",
      "Match each planned post to an appropriate format. For each post, decide if/how to use images based on content type and platform norms.",
    ].join("\n");

    try {
      const providerConfig = resolveProviderConfig(this.env.GOOGLE_API_KEY);
      const models = createAdvancedModelChain(providerConfig);

      const result = await generateObject({
        model: models[0],
        system: systemPrompt,
        prompt,
        schema: ORCHESTRATOR_SCHEMA,
        temperature: 0.7,
        maxOutputTokens: 1200,
      });
      return normalizeResponse(result.object, input.renderPolicy);
    } catch (error) {
      console.warn("[marketing-orchestrator] generateObject failed, using fallback:", error);
      return fallbackResponse(input);
    }
  }
}

function fallbackResponse(input: OrchestratorRequestPayload): OrchestratorResponsePayload {
  const formatSummary = input.requestedFormats.join(", ") || "requested formats";
  const formatList = input.requestedFormats.length > 0 ? input.requestedFormats : ['linkedin', 'twitter', 'instagram'];
  const postCount = input.postCount || Math.min(formatList.length, 3);
  const imageMode = input.imageConfig?.mode || 'auto';
  
  // Map common formats to dimensions
  const formatDims: Record<string, { width: number; height: number }> = {
    linkedin: { width: 1200, height: 627 },
    twitter: { width: 1200, height: 675 },
    instagram: { width: 1080, height: 1080 },
    facebook: { width: 1200, height: 630 },
    pinterest: { width: 1000, height: 1500 },
  };
  
  // Generate fallback planned posts
  const plannedPosts: PostBrief[] = formatList.slice(0, postCount).map((format) => {
    const dims = formatDims[format.toLowerCase()] || { width: 1200, height: 630 };
    
    // Default image spec based on image mode
    let imageSpec: ImageSpec | undefined;
    if (imageMode !== 'none') {
      imageSpec = {
        type: imageMode === 'ai' ? 'background' : 'none',
        position: 'background',
        count: 1,
        style: 'minimal',
      };
    }
    
    return {
      format,
      brief: `Create a ${format} post highlighting key insights from the source content.`,
      copyFocus: "Clear, platform-native copy with strong hook",
      visualDirection: input.renderPolicy.allowTextInAiImages
        ? "Clean editorial visual aligned to message"
        : "Editorial visual with negative space, no text artifacts",
      cta: input.settings?.campaign?.cta || "Learn more",
      imageMode: imageMode,
      imageSpec,
      width: dims.width,
      height: dims.height,
    };
  });

  return {
    strategic_brief: `Create platform-native assets for ${formatSummary} with clear hooks, practical middle content, and concrete CTA endings.`,
    copywriter_notes: "Write concise platform-native copy, complete sentences, and non-repetitive angles. Keep captions informative and conversion-oriented.",
    visual_notes: input.renderPolicy.allowTextInAiImages
      ? "Use clean editorial visuals aligned to the message."
      : "Use clean editorial visuals with intentional negative space. Never include text artifacts in generated images.",
    warnings: ["orchestrator_fallback_used"],
    plannedPosts,
  };
}

function normalizeResponse(
  raw: Record<string, unknown>,
  policy: RenderPolicyPayload
): OrchestratorResponsePayload {
  const warnings = toStringArray(raw.warnings);
  if (!policy.allowTextInAiImages) {
    warnings.push("no_text_in_ai_images_enforced");
  }

  // Map common formats to dimensions
  const formatDims: Record<string, { width: number; height: number }> = {
    linkedin: { width: 1200, height: 627 },
    twitter: { width: 1200, height: 675 },
    instagram: { width: 1080, height: 1080 },
    facebook: { width: 1200, height: 630 },
    pinterest: { width: 1000, height: 1500 },
  };

  // Normalize planned posts
  let plannedPosts: PostBrief[] | undefined;
  const rawPlannedPosts = raw.plannedPosts;
  if (Array.isArray(rawPlannedPosts)) {
    plannedPosts = rawPlannedPosts.map((post: any) => {
      const format = post.format || 'linkedin';
      const dims = formatDims[format.toLowerCase()] || { width: 1200, height: 630 };
      
      // Normalize image spec
      let imageSpec: ImageSpec | undefined;
      if (post.imageSpec) {
        imageSpec = {
          type: post.imageSpec.type || 'none',
          prompt: post.imageSpec.prompt,
          position: post.imageSpec.position || 'background',
          count: post.imageSpec.count || 1,
          style: post.imageSpec.style,
        };
      }
      
      return {
        format,
        brief: toSingleLine(post.brief, "Create engaging social post."),
        copyFocus: toSingleLine(post.copyFocus, "Clear, platform-native copy."),
        visualDirection: toSingleLine(post.visualDirection, "Clean editorial visual."),
        cta: toSingleLine(post.cta, "Learn more"),
        imageMode: post.imageMode || 'auto',
        imageSpec,
        width: post.width || dims.width,
        height: post.height || dims.height,
      };
    });
  }

  return {
    strategic_brief: toSingleLine(raw.strategic_brief, "Focus on platform-native strategy."),
    copywriter_notes: toSingleLine(raw.copywriter_notes, "Write concise and complete platform-native copy."),
    visual_notes: toSingleLine(raw.visual_notes, "Use clean text-safe editorial backgrounds with no generated text artifacts."),
    warnings: [...new Set(warnings.map((item) => item.trim()).filter(Boolean))].slice(0, 8),
    plannedPosts,
  };
}

async function parseRequestPayload(request: Request): Promise<OrchestratorRequestPayload | null> {
  try {
    const data = await request.json();
    if (!data || typeof data !== "object" || Array.isArray(data)) {
      return null;
    }
    return data as OrchestratorRequestPayload;
  } catch {
    return null;
  }
}

function toStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map((item) => (typeof item === "string" ? item.trim() : "")).filter(Boolean);
}

function toSingleLine(value: unknown, fallback: string): string {
  if (typeof value !== "string") return fallback;
  const compact = value.replace(/\s+/g, " ").trim();
  return compact || fallback;
}

function json(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" }
  });
}

// ─── Standalone function for calling orchestrator from pipeline ─────────────────

export interface OrchestratorInput {
  post: {
    title: string;
    excerpt?: string;
    plaintext?: string;
    tags?: string[];
  };
  requestedFormats: string[];
  userPrompt?: string;
  promptProfile: PromptProfilePayload;
  renderPolicy: RenderPolicyPayload;
  postCount?: number;
  settings?: WorkspaceSettings;
  imageConfig?: {
    mode: string;
  };
}

export interface OrchestratorOutput {
  strategic_brief: string;
  copywriter_notes: string;
  visual_notes: string;
  warnings: string[];
  plannedPosts: PostBrief[];
}

export async function callOrchestrator(
  input: OrchestratorInput,
  ai: Ai,
  googleApiKey?: string
): Promise<OrchestratorOutput> {
  const payload: OrchestratorRequestPayload = {
    post: input.post,
    requestedFormats: input.requestedFormats,
    userPrompt: input.userPrompt,
    promptProfile: input.promptProfile,
    renderPolicy: input.renderPolicy,
    postCount: input.postCount,
    settings: input.settings,
    imageConfig: input.imageConfig,
  };

  const providerConfig = resolveProviderConfig(googleApiKey);
  const models = createAdvancedModelChain(providerConfig);

  const sourceBody = (input.post.plaintext ?? "").trim();
  const sourceExcerpt = (input.post.excerpt ?? "").trim();
  const sourceText = sourceBody || sourceExcerpt;
  const truncatedSource = sourceText.length > 14000 ? `${sourceText.slice(0, 14000)}...` : sourceText;

  const tags = (input.post.tags ?? []).slice(0, 8).join(", ");
  const requestedFormats = input.requestedFormats.join(", ");
  const userPrompt = input.userPrompt?.trim() || "(none)";
  const postCount = input.postCount || input.requestedFormats.length;

  const settings = input.settings || {};
  const imageConfig = input.imageConfig || { mode: 'auto' };
  
  const brandInfo = settings.brand ? 
    `Brand: ${settings.brand.name || 'unnamed'} | Tone: ${settings.brand.tone || 'neutral'} | Audience: ${settings.brand.audience || 'general'}` : 
    'Brand: not configured';
  const campaignInfo = settings.campaign ?
    `Goal: ${settings.campaign.goal || 'awareness'} | Framework: ${settings.campaign.framework || 'none'} | CTA: ${settings.campaign.cta || 'none'}` :
    'Campaign: not configured';
  const imageMode = imageConfig.mode || 'auto';

  const policyNotes = [
    `allow_markdown=${input.renderPolicy.allowMarkdown}`,
    `allow_math=${input.renderPolicy.allowMath}`,
    `allow_diagrams=${input.renderPolicy.allowDiagrams}`,
    `allow_text_in_ai_images=${input.renderPolicy.allowTextInAiImages}`
  ].join(", ");

  const systemPrompt = [
    ...input.promptProfile.mastermind,
    ...input.promptProfile.strategist,
    ...input.promptProfile.copywriter,
    ...input.promptProfile.visualDirector,
    ...input.promptProfile.renderGuard,
    "Return strict JSON matching the required response schema."
  ].filter(Boolean).join("\n");

  const prompt = [
    `Build a creative campaign orchestration decision for social content generation.`,
    "",
    `IMPORTANT: Plan ${postCount} posts from this content.`,
    "",
    `=== CONFIGURATION ===`,
    brandInfo,
    campaignInfo,
    `Image mode: ${imageMode} (options: auto, none, feature, ai)`,
    `Available formats: ${requestedFormats || "(none)"}`,
    "",
    `=== CONTENT ===`,
    `<title>${input.post.title.trim()}</title>`,
    `<excerpt>${sourceExcerpt || "(none)"}</excerpt>`,
    `<tags>${tags || "(none)"}</tags>`,
    "<body>",
    truncatedSource || "(none)",
    "</body>",
    "",
    `=== RENDER POLICY ===`,
    policyNotes,
    "",
    `User prompt: ${userPrompt}`,
    "",
    "Produce:",
    "- strategic_brief: campaign intent, creative angle, and hook strategy",
    "- copywriter_notes: platform tone, structure, and copy direction",
    "- visual_notes: image direction and composition guidance",
    "- warnings: potential quality/compliance risks",
    "",
    `IMPORTANT: Also produce a "plannedPosts" array with ${postCount} entries, one for each planned post. Each entry should have:`,
    "- format: the social platform/format - MUST be one of: " + (requestedFormats || 'linkedin,twitter,instagram'),
    "- brief: a 1-2 sentence creative brief for this specific post",
    "- copyFocus: what angle/perspective to take for the copy",
    "- visualDirection: visual style guidance for this post (consider image mode: " + imageMode + ")",
    "- cta: specific call-to-action for this format",
    "- imageMode: recommended image generation mode (auto/none/feature/ai). If set to 'ai', you MUST provide an imageSpec and a detailed prompt.",
    "- imageSpec: detailed image specification with:",
    "  * type: background | illustration | pattern | gradient | feature | none",
    "  * prompt: AI generation prompt. REQUIRED if imageMode is 'ai'. Describe visual, no text.",
    "  * position: background | hero | left | right | overlay",
    "  * count: number of images for carousel (1-5)",
    "  * style: style hints (minimal, bold, abstract, realistic, etc.)",
    "- width: recommended width for this format",
    "- height: recommended height for this format",
    "",
    "Match each planned post to an appropriate format. For each post, decide if/how to use images based on content type and platform norms.",
  ].join("\n");

  try {
    const result = await generateObject({
      model: models[0],
      system: systemPrompt,
      prompt,
      schema: ORCHESTRATOR_SCHEMA,
      temperature: 0.7,
      maxOutputTokens: 1200,
    });
    
    const response = normalizeResponse(result.object, input.renderPolicy);
    return {
      strategic_brief: response.strategic_brief,
      copywriter_notes: response.copywriter_notes,
      visual_notes: response.visual_notes,
      warnings: response.warnings,
      plannedPosts: response.plannedPosts || [],
    };
  } catch (error) {
    console.warn("[callOrchestrator] generateObject failed, trying text fallback:", error);
    try {
      const { generateText } = await import("ai");
      const textResult = await generateText({
        model: models[0],
        system: systemPrompt,
        prompt,
        temperature: 0.7,
        maxOutputTokens: 1200,
      });

      const jsonMatch = textResult.text.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        const validated = ORCHESTRATOR_SCHEMA.safeParse(parsed);
        if (validated.success) {
          const response = normalizeResponse(validated.data, input.renderPolicy);
          return {
            strategic_brief: response.strategic_brief,
            copywriter_notes: response.copywriter_notes,
            visual_notes: response.visual_notes,
            warnings: response.warnings,
            plannedPosts: response.plannedPosts || [],
          };
        }
      }
    } catch (textError) {
      console.warn("[callOrchestrator] Text fallback also failed:", textError);
    }
    console.warn("[callOrchestrator] Using fallback response");
    return fallbackResponse(payload) as OrchestratorOutput;
  }
}
